DATASET:
  TRANSFORMS:
    CENTER_CROP:
    - 50
    - 50
    RESIZE:
    - 224
    - 224
TRAINING:
  MODEL:
    NAME: vit_l_32
    REGISTRY: OCCUPANCY_CLASSIFIER
_BASE_: config://occupancy_classifier/_base_pretrained.yaml
